### ISSUE TITLE
Test and document the RotateableBlockFamily

### ISSUE THREAD

**Issue by oniatus** [Terasology/TutorialAssetSystem#1]
The family works in principle but the concept needs a good documentation and testing.
The [RotateableBlockFamily](https://github.com/Terasology/TutorialAssetSystem/wiki/RotateableBlockFamily)-page will be used for this.
I am pretty sure, some rotations will map to the wrong sides in the current state :)

**Comment by jdrueckert** [comment]
The only rotation related block family I could find is [`FullRotationFamily`](https://github.com/Terasology/BlockNetwork/blob/develop/src/main/java/org/terasology/blockNetwork/block/family/FullRotationFamily.java) in the `BlockNetwork` module which is only used by blocks of the `Signalling` module.
Considering that the wiki does not provide documentation for any specific block family at the moment, I don't think we should emphasize this block family in particular, so I'll close this issue to increase visibility of other more relevant issues in module land.
