### ISSUE TITLE
Wiki tutorial fetch module command does not work.

### ISSUE THREAD

**Issue by gatoWololo** [Terasology/TutorialAssetSystem#12]
It seems the wiki command `gradlew fetchModuleTutorialAssetSystem` no longer works? I used `groovyw module get TutorialAssetSystem` instead.

**Comment by gatoWololo** [comment]
It seems to be correct in the `Setup` page: https://github.com/Terasology/TutorialAssetSystem/wiki/Setup

but not in the home page:

> Every step from the tutorial is reflected in the module hosted in this repository. You should be able to fetch the entire module via gradlew fetchModuleTutorialAssetSystem. It is not required to follow the tutorial but can be used to get a quick overview.

**Comment by Cervator** [comment]
Nice catch! You are correct. Just fixed it in the wiki. There are likely other outdated spots like this so please let us know when you find them! In some cases you might be able to edit the wikis yourself, we keep the edit settings pretty open :-)

Closing as fixed.

**Comment by gatoWololo** [comment]
Great. I'll fix it in little places when I can :)

**Comment by skaldarnar** [comment]
Great to see you found the way to the wikis and already improved it @gatoWololo - highly appreciated! 💚
