### ISSUE TITLE
Document @AddToBlockBasedItem Annotation

### ISSUE THREAD

**Issue by BeksOmega** [Terasology/TutorialAssetSystem#9]
### What

The `@AddToBlockBasedItem` annotation is appended to a `Component` class. When the `BlockItemFactory` finds a component with this annotation on the Block's prefab, it knows to mix it into the BlockItem.

### Suggested Content

There should be information about:
* What the annotation does.
* Where to put it (on the `Component` class).
* Possibly an example of when you would want to use it.

This could be added to one of the chapters, or maybe made into its own chapter.

### Requested Assignment

If possible, I would like to fix this. With a little guidance about where to put it, and how much to include =)

**Comment by BeksOmega** [comment]
Added a wiki page [here](https://github.com/Terasology/TutorialAssetSystem/wiki/Adding-Components-to-a-Block-Based-Item). I think the example is pretty good, but if anything needs changes please tell me!

**Comment by Cervator** [comment]
Heya @BeksOmega - thanks a lot for both submitting the issue _and_ fixing it, and apologies for entirely missing it up until just now! We coincidentally added this annotation somewhere else just recently and I got to thinking 🤔 hmm we should doc this somewhere 🤔 

And guess what - somebody already did! Much appreciated :-)

If you're curious it might also be of use to actually implement an example block/item in this repo to then refer a reader to for a working example. And/or help slot this new page into a step-by-step introduction like the main page in the wiki attempts to do for _some_ pages at least :-)

Our Discord at https://discord.gg/terasology is a fair bit easier to communicate with for sure, less chance of being missed. Come say hi sometime if you like! 👍
